initial commit-added a sync script and command
metron-labs/metron-demisto-content pull request #422
Opened 2022-10-31 13:24 UTC by anirudh-metron

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-11-01 06:06 UTC, saurabh-metron commented on Packs/SentinelOne/Scripts/SyncXSOARSentinelOneIncidents/SyncXSOARSentinelOneIncidents.py
> +            # print(xsoar_s1_incidents)
remove commented code from everywhere, please check

2022-11-01 06:07 UTC, saurabh-metron commented on Packs/SentinelOne/Scripts/SyncXSOARSentinelOneIncidents/SyncXSOARSentinelOneIncidents.py
> +        # ToDo - Throw exception from here
Please check this ToDo, and remove this comment post its done

2022-11-01 06:09 UTC, saurabh-metron commented on Packs/SentinelOne/Playbooks/SyncXSOARToSentinelOneIncidents.yml
> +      scriptName: SyncXSOAR-SentinelOneIncidents
script names are changed, please check.
I would suggest Test you package once on XSOAR, delete everything on the XSOAR and push your content pack and test once

2022-11-01 06:15 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
> +```!sentinelone-get-threats-info threat_ids=<value>```
At the end of this, please mention how the user should use playbooks.
And which playbooks to be used for which operation, mention the steps and job details, etc

2022-11-01 11:28 UTC, munna-metron requested changes

2022-11-01 11:28 UTC, munna-metron commented on Packs/SentinelOne/Playbooks/SyncSentinelOneToXSOARIncidents_README.md
> +![Playbook-SyncXSOAR-SentinelOneIncidents](../doc_files/Playbook-SyncXSOAR-SentinelOneIncidents.png)
check the preview in the github, you need to push the png image to the GitHub

2022-11-01 11:28 UTC, munna-metron commented on Packs/SentinelOne/Playbooks/SyncXSOARToSentinelOneIncidents_README.md
> +![Playbook-SyncXSOAR-SentinelOneIncidents](../doc_files/Playbook-SyncXSOAR-SentinelOneIncidents.png)
same here too

2022-11-01 11:28 UTC, anirudh-metron commented on Packs/SentinelOne/Playbooks/SyncSentinelOneToXSOARIncidents_README.md
> +![Playbook-SyncXSOAR-SentinelOneIncidents](../doc_files/Playbook-SyncXSOAR-SentinelOneIncidents.png)
Done

2022-11-01 11:32 UTC, anirudh-metron commented on Packs/SentinelOne/Playbooks/SyncXSOARToSentinelOneIncidents_README.md
> +![Playbook-SyncXSOAR-SentinelOneIncidents](../doc_files/Playbook-SyncXSOAR-SentinelOneIncidents.png)
Done

2022-11-09 10:08 UTC, saurabh-metron approved these changes

2022-11-09 10:09 UTC, merged