Add epp malop and changed version 2.0.1
metron-labs/metron-demisto-content pull request #519
Opened 2022-12-23 12:56 UTC by ritesh-metron

added epp malop incidents for polling

2022-12-26 05:29 UTC, kapil-metron requested changes

2022-12-26 05:29 UTC, kapil-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +        demisto.info(f"EPP value: {IS_EPP_ENABLED}")
All info() messages should be a readable sentence. In this case it should be:
"Fetching EPP malop is enabled: {IS_EPP_ENABLED}"

2022-12-26 05:29 UTC, kapil-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +        demisto.info(f"EPP value: {IS_EPP_ENABLED}")
This applies to all info level messages, as these messages are meant for enduser. These messages should be grammatically correct and complete sentense.
In the other hand Debug messages can be technical, as they are meant for developers, who is debugging the app.

2022-12-26 05:29 UTC, kapil-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.yml
>    - arguments:
Why these fields been removed?

2022-12-26 16:53 UTC, suraj-metron requested changes

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.yml
> +fromversion: 5.0.0
Please add a newline after this

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.yml
> +  description: Enable EPP Poll for incidents.
Update the description to: "Check this box to Enable Polling for Cybereason EPP Malops"

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +from CommonServerPython import *
There are extra spaces added after import, is it part of some linting? If not, please revert

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +def rest_malops(client: Client,start_time):
change function name to: poll_malops
Add a space before start_time function parameter.

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +def get_non_edr_list(client,start_time):
Why we need to create a list for EDR Malops? Is it required? If not, please remove it.
Change function name to: get_non_edr_malop_data

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +    malop_list = rest_malops(client,start_time)
Please change variable name to: malop_data

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +    non_edr_list = list()
Change the variable name to: non_edr_malop_data

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +    for guid in malop_list['malops']:
Change the for loop to: for malops in malop_list['malops']

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +    demisto.debug(f"Fetching the length of edr guid list: {len(edr_malop_guid)}")
After the for loop, free/empty the malop_list(malop_data) variable as we are not using it further. This variable contains all Malop data so it might cause memory overflow.

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +    demisto.debug(f"Fetching the length of non-edr list: {len(non_edr_list)}")
Change this log to: f"Total length of EPP Malops fetched is: {len(non_edr_list)}"

2022-12-26 16:53 UTC, suraj-metron commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +            malop_update_time = non_edr_malops['lastUpdateTime']
Use dict_safe_get here as we did for non-epp

2023-01-02 13:16 UTC, suraj-metron approved these changes

2023-01-02 13:44 UTC, merged