Added filter option to fetch Threats and bug fix
metron-labs/metron-demisto-content pull request #607
Opened 2023-08-30 09:29 UTC by anirudh-metron

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2023-08-30 10:21 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +        if len(site_ids) != 0:
avoid using all these if else statements

payload["filter"] = {
    filterKey: filterValue
    for filterKey, filterValue in {
        "siteIds": site_ids,
        "groupIds": group_ids,
        "accountIds": account_ids
    }.items()
    if filterValue is not None
}

how about this dictionary comprehension?
This code creates a new dictionary for payload["filter"] using a dictionary comprehension. It only includes dict pair pairs where the value is not None. This way, if group_ids are not present, the corresponding key-value pair for "groupIds" will be excluded from the dictionary.
Try including it and test it as well

2023-08-30 10:22 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +        if len(site_ids) != 0:
and it repeats twice, why not create a function and use it in both cases, to reuse the same code?

2023-08-30 10:32 UTC, anirudh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +        if len(site_ids) != 0:
okay

2023-08-30 11:29 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +    def create_filter_dict(self, filter_keys, filter_values):
```suggestion
    def _create_filter_dict(self, filter_keys, filter_values):
```
this tell the reader that its a private method

2023-08-30 11:29 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +        filter_keys = ["siteIds", "groupIds", "accountIds"]
also what is this :) 
create a dictionary rather than 2 lists

2023-08-30 11:30 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +        filter_keys = ["siteIds", "groupIds", "accountIds"]
this is not ideal - use an appropraite dataStructure to create a map 
use dictionary

2023-08-31 05:45 UTC, munna-metron approved these changes
LGTM

2023-08-31 06:03 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +            if len(filter_value) != 0
```suggestion
            if filter_value
```
this would look more cleaner, wouldn't it?
As you are checking if the `filter_value` exists or not

2023-08-31 06:06 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
> +- name: fetch_threat_incident_statuses
can we do a default value here?
try to do a backwards compatibility test to check if you upgrade the older installation doesn't break
meaning it should still work like before

Also you mentioned the API for threat expects lower case values for calls, make sure these values don't break anything as you have not converted them anywhere

2023-08-31 06:07 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
> +| incidentStatuses | Incident status. Example: "in_progress". | Optional |
is the example correct?
should this be in all caps? why is this out of sync?

2023-08-31 06:08 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +            incidentStatuses=argToList(incidentStatuses)
```suggestion
            incident_statuses=argToList(incidentStatuses)
```
shouldn't this be camel cased? similar to other naming conventions?
please keep the convention same as before

2023-08-31 06:08 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +                            include_resolved_param=True, incidentStatuses=None):
```suggestion
                            include_resolved_param=True, incident_statuses=None):
```
why are we changing the convention?

2023-08-31 06:09 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
> +| incidentStatuses | Incident status. Example: "in_progress". | Optional |
incident_statuses - also covention should not be changed, please make sure of that

2023-08-31 06:10 UTC, saurabh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
> +    - description: 'Incident status. Example: "in_progress".'
hope the example is correct here as well

2023-09-01 05:05 UTC, anirudh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
> +- name: fetch_threat_incident_statuses
updated and check with everything, also i added .lower() whenever parameter is fetched from args. inside the function for  get-threats.

2023-09-01 06:02 UTC, anirudh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
> +    - description: 'Incident status. Example: "in_progress".'
updated all the review comments yesterday itself.waiting for approval, Thanks.

2023-09-01 06:03 UTC, saurabh-metron approved these changes

2023-09-06 06:49 UTC, kapil-metron requested changes
Please check a comment I have posted.
Please also confirm no Unit test are to be updated for the recent changes.

2023-09-06 06:49 UTC, kapil-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +    resolved = 'true' if incident_statuses and 'RESOLVED' in incident_statuses else 'false'
Are we sure the incident_statuses will always have strings in upper case only. If not we may need the following code:
if 'RESOLVED' in (status.upper() for status in incident_statuses):

2023-09-06 07:04 UTC, anirudh-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +    resolved = 'true' if incident_statuses and 'RESOLVED' in incident_statuses else 'false'
yes, it will always be upper case only as they are selected based on the options provided during configuration.

2023-09-06 07:19 UTC, parag-metron approved these changes

2023-09-06 07:26 UTC, kapil-metron approved these changes

2023-09-06 08:21 UTC, merged