Devo v1.2.3
metron-labs/metron-demisto-content pull request #608
Opened 2023-08-30 09:43 UTC by manas-metron

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2023-08-30 11:14 UTC, pavel-razgovorov requested changes
Here are some things that I found.

Besides that, I am also missing any new tests. Every time a new functionality is introduced, it must come on hand with at least one new test case that verifies it, especially when a bug is solved.

2023-08-30 11:14 UTC, pavel-kalmykov commented on Packs/Devo/ReleaseNotes/1_2_7.md
> +- Created new parameter Fetch Incident Time Frame in yml file.
**suggestion(blocking):** Please, specify why are these new parameters introduced, what they are used for, and what these additions solve/enable.

2023-08-30 11:14 UTC, pavel-razgovorov commented on Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
> +  - display: Fetch Incidents Lookback Time (in seconds). (Should be between 3600 (1 hour) to 86400 (24 hours).)
```suggestion
  - display: Fetch Incidents Lookback Time (in seconds). Must be between 3600 (1 hour; default) to 86400 (24 hours).
```

2023-08-30 11:14 UTC, pavel-kalmykov commented on Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
> +  - display: Custom Alert Table name(If not provided, 'siem.logtrust.alert.info' will be used.)
```suggestion
  - display: Custom Alert Table name (if not provided, 'siem.logtrust.alert.info' will be used)
```

2023-08-30 11:14 UTC, pavel-kalmykov commented on Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
> +  - display: Custom Alert Table prefix (Provide prefix if custom table name provided.)
```suggestion
  - display: Custom Alert Table prefix (provide prefix if custom table name provided)
```

2023-08-30 11:14 UTC, pavel-razgovorov commented on Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
> +  - display: Fetch Incident Limit(Should be between 10 and 100. Advisable 50 for better performance.)
```suggestion
  - display: Fetch Incident Limit (must be between 10 and 100; advisable 50 for better performance)
```

2023-08-30 11:14 UTC, pavel-razgovorov commented on Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
> +  - display: Fetch Incident Time Frame (Should be in seconds)
```suggestion
  - display: Fetch Incident Time Frame (in seconds)
```

2023-08-30 11:14 UTC, pavel-razgovorov commented on Packs/Devo/Integrations/Devo_v2/README.md
> +    * __Fetch Incident Time Frame__ (Should be in seconds).
```suggestion
    * __Fetch Incidents Lookback Time (in seconds)__ Must be between 3600 (1 hour) to 86400 (24 hours). Default: 3600.
    * __Fetch Incident Time Frame (in seconds)__.
```

2023-08-30 11:14 UTC, pavel-kalmykov commented on Packs/Devo/Integrations/Devo_v2/Devo_v2_test.py
> +MOCK_WRITER_ARGS1 = {
**suggestion:** Please, use a more descriptive name.

2023-08-30 14:46 UTC, pavel-kalmykov requested changes

2023-08-30 14:46 UTC, pavel-kalmykov commented on Packs/Devo/ReleaseNotes/1_2_7.md
> +- Created new parameter Fetch Incident Time Frame in yml file.This parameter is used to set window lookback time.Whenever this parameter is set it will set the from_time to use the window to pull all
```suggestion
- Created new parameter Fetch Incidents Lookback Time in yml file. This parameter specifies the time in past from which you wish to retrieve alerts.
- Created new parameter Fetch Incident Time Frame in yml file. This parameter is used to set window lookback time. Whenever this parameter is set it will set the `from_time` to use the window to pull all alerts.
```

2023-08-31 08:09 UTC, kapil-metron approved these changes

2023-08-31 08:10 UTC, merged