update analyst verdict for both alerts and threats
metron-labs/metron-demisto-content pull request #77
Opened 2022-04-05 07:23 UTC by munna-metron

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-06-06 07:02 UTC, devang-metron requested changes

2022-06-06 07:02 UTC, devang-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
> +      - events
There are also processes as query type. Why haven't we added that?

2022-06-06 07:02 UTC, devang-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
> +      predefined:
There are also processes as query type. Why haven't we added that?

2022-06-06 07:02 UTC, devang-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +                    "networkQuarantine": network_quarantine,
Please check if this is working fine. As you have passed them as a string rather than boolean from the command.

2022-06-06 08:09 UTC, munna-metron commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
> +                    "networkQuarantine": network_quarantine,
checked it's working fine.

2022-06-07 06:51 UTC, devang-metron approved these changes

2022-06-07 06:54 UTC, merged